### ISSUE TITLE
Use cakephp 3 phpcs template?

### ISSUE THREAD

**Issue by kevinquinnyo** [FriendsOfCake/Authenticate#47]
I notice the code in the cake3 branch does not conform to the cakephp 3 phpcs standards.  (docblocks and tab/spacing mostly)  Shouldn't it?

Is there any reason it doesn't?  If I want to make a PR for something, should I conform to the current style?  Or use the cakephp 3 standards?

If this is just something on the to-do list, let me know.  I don't mind helping to make the 'cake3' branch conform to the cakephp 3 phpcs template.

**Comment by ADmad** [comment]
A PR to update code to new coding standard is welcome.

**Comment by kevinquinnyo** [comment]
build failed because travis CI is using a different phpcs template I believe

**Comment by ADmad** [comment]
Closing as PR is opened.
