### ISSUE TITLE
CookieAuthenticate refactor for ephemeral token

### ISSUE THREAD

**Issue by kevinquinnyo** [FriendsOfCake/Authenticate#53]
For some reason I keep revisiting my Authentication stuff and I have a some questions.

First, @ADmad thanks for taking care of breaking apart `_findUser()` in cakephp's BaseAuthenticate :+1: 

In a private cakephp project I'm working on, even though the cookie itself is encrypted, I'm not comfortable storing a username and password in it.  So I use a `uuid` field and a `remember_me_token` field for `username` and `password`, respectively.  This is only superficially more secure in that it's essentially the same things with different values.  But it does help that I can null out/invalidate the `remember_me_token` field because I also have a `remember_me_token_created` field.  (which also guards against cookie tampering of the cookie expiration time)  Also in the off-chance that a cookie is either not encrypted, and/or is compromised/hijacked, all the hacker has is two random strings, instead of having a username/password combo, which is slightly better.  (they have to resort to brute-force)

So I was thinking about modifying CookieAuthenticate to allow an optional token_created field that represents the "remember me token creation time", making the "remember me token" ephemeral. (better)

When working through this in my head, I keep thinking it would be better if the fields were changed:

  `username` becomes `identifier`
  `password` becomes `token`

And an additional, optional fields key:

  `token_created` (datetime)

It could probably be done in a way that does not break backwards compatibility.  Does anyone have any thoughts on this?  I don't want to introduce "config bloat" or "BC spaghetti" for a security issue, if there's a better approach to this basically.

Also, I am starting to wonder why some of these classes aren't core cakephp.  "Remember Me / Cookie" auth seems to be popular enough to warrant inclusion.  Probably the same goes for Token Auth?  It would avoid the additional dependency on `FOC` for projects.  Then `FOC/Authenticate` could focus on non-standard/special authentication classes.

Anyway, I was inspired when reading up on the issue of "cookie/remember-me" authentication techniques, specifically the highest voted answer here:

http://stackoverflow.com/questions/244882/what-is-the-best-way-to-implement-remember-me-for-a-website

And this referenced link:

https://paragonie.com/blog/2015/04/secure-authentication-php-with-long-term-persistence#title.2

I'm not worried about the edge-case timing attacks and such.  That can and should be a developer's job to defend against if they are worried about that.

Anyway , sorry for the wall of text.

**Comment by ADmad** [comment]
[This](https://github.com/cakephp/cakephp/pull/6664) PR paves the path for having cookie based login in core itself :)  Since you have see to have done the related research would you like to give at shot at making Auth\Storage\CookieStorage class?

As for token based authenticate I would suggest just using [ADmad\JwtAuth](https://github.com/cakephp/cakephp/pull/6664) which uses industry standard JSON Web Tokens. The reason I wouldn't include it in core is because it has an external dependency and we try to avoid those as far as possible.

**Comment by kevinquinnyo** [comment]
That's interesting.  I could certainly give it a shot.  Would it make sense in the constructor of a CookieStorage class to throw `\Cake\Controller\Exception\MissingComponentException` if an instance of CookieComponent is not loaded on `$request->controller`?  Or should that still be the role of a CookieAuthenticate class (or anything else downstream that needs that component)?

I'm also trying to map out the roles of the classes in the hypothetical case of building a Cookie storage class and a Cookie Authenticate class based on it.

Currently, here in `FOC\CookieAuthenticate`, the cookie data is read as a means to *then* simply write the user record to the session (which seems like the only sane way to handle this to me), so it seems it would still use the SessionStorage class for AuthComponent as opposed to a CookieStorage class.

I understand the benefit of taking the hardcoded session out of AuthComponent and injecting swappable storage classes, but I'm having trouble figuring out what the role should be for a CookieStorage class I guess.  I think it's weird to me because the Cookie data should really just be viewed as reference data that can be used as an intermediary to writing and deleting session keys.

Would it make sense if `CookieStorage::write()` *also* writes to the session?  Or would it make more sense that in `Auth\CookieAuthenticate`, the `AuthComponent::storage()` method is used to switch to to 'Cookie' storage type, read/write the cookie, then switch it back to 'Session' type and read/write the session?

Does this make sense what I'm asking?

**Comment by ADmad** [comment]
Yeah, a `CookieStorage` isn't absolutely necessary. A `CookieAuthenticate` class like the one this plugin has should suffice. Though instead of storing username and password an identifier and token could be stored in cookie.

If we were to make a `CookieStorage` it probably should read / write to cookie and session both. Though to encrypt the cookie you need `CookieComponent` and the auth storage classes only have access to request and response objects, no reference to controller or component registry.

**Comment by kevinquinnyo** [comment]
I decided to play around with the ideas here : https://github.com/kevinquinnyo/Authenticate/commit/ba814ef36f8d5db8b2b1503aeae676ad99e2ea4f but there are a few questionable lines of code I think.  For instance this part that checks the tokenCreated field in `src/Auth/CookieAuthenticate.php`:

```
if ($tokenCreated !== null) {
    $expiration = str_replace('+', '', $this->config('cookie.expires'));
    if (!$user[$tokenCreated]->wasWithinLast($expiration)) {
        return false;
}
```
There's probably a better way to do that I'm guessing.  Also needs more tests.  Forgot to write one with an intentionally tampered cookie expiry.

I'm curious, if something similar to this were to make it's way into cakephp, what's the best way to do that?  Make a branch here, change the license in the header and such, and have FOC submit a PR?  Or just create a branch on a user account and submit the PR from there?

There's absolutely no rush on any of this by the way, I was just bored today and wanted to mess around with it.

**Comment by kevinquinnyo** [comment]
I did forget to change the keys to:

'identifier' (usernamey type thing, plaintext, defaults to username)
'token' (passwordy type thing, hashed, defaults to password).
(optional) 'tokenCreated' (datetime)

I guess a better version of this would use those keys for configuration so that it's more clear what's happening, and how to use.

**Comment by ADmad** [comment]
> I'm curious, if something similar to this were to make it's way into cakephp, what's the best way to do that? Make a branch here, change the license in the header and such, and have FOC submit a PR? Or just create a branch on a user account and submit the PR from there?

Just create a branch on your account and PR it to cake core (to 3.1 branch). Change the license to match those used by other core files.

**Comment by jadb** [comment]
Closing as PR is now open.

**Comment by davidyell** [comment]
:+1:
