### ISSUE TITLE
Add support for custom finder as per cake 3.1

### ISSUE THREAD

**Issue by birdy247** [FriendsOfCake/Authenticate#56]
Since cake 3.1 it is suggested to use a custom find method to modify the query to find a user (as opposed to Scope)

http://book.cakephp.org/3.0/en/controllers/components/authentication.html#customizing-find-query

It would be great if this plugin could utilise this functionality.

Thanks

**Comment by ADmad** [comment]
Make a PR :)

**Comment by ceeram** [comment]
Closing as no solution has been provided and the maintainers no longer actively maintain the cake3 branch, see also: https://github.com/FriendsOfCake/Authenticate/issues/58
