### ISSUE TITLE
Missing configuration step?

### ISSUE THREAD

**Issue by urionlinejudge** [FriendsOfCake/Authenticate#57]
I followed the configuration steps and when using both Cookie then Multicolumn, the Cookie itself never works. It always falls back to the Multicolumn. Is there any other steps?

The cookie itself is being created and hashed. However, it is not used to log the user in.

**Comment by birdy247** [comment]
I am also having this "problem".  Cake 3.  The cookie is created, but it does not log the user in.

**Comment by birdy247** [comment]
I have resolved this.  I was assuming that the cookie keys needed to be username/password.  However, I identify with email/password.  Changing this in _setCookie resolved the issue.  Great plugin!
