### ISSUE TITLE
Cake 3 release

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/Authenticate#58]
Please can a release be pushed for the Cake 3 version and updated to Packagist

Thanks!

**Comment by burzum** [comment]
:+1:

**Comment by ADmad** [comment]
I am curious which authenticate class of this plugin people are popularly using for 3.1.

TokenAuth is poor man's JwthAuth, MultiAuth can be achieved with custom finder in 3.1 and for CookieAuth there is alternative like Xety/Cake3-CookieAuth. So do we really want to maintain 3.x compatible branch of this plugin?

**Comment by davidyell** [comment]
If the decision is taken to not maintain it, the readme should be updated with the other projects to direct users. Personally, I wasn't aware of the alternatives, and I tend to rate the FoC stuff higher than other peoples plugins, just because it's a bit more official.

**Comment by bravo-kernel** [comment]
I'm using it for the `identificationColumns` multi column authentication. Do I understand correctly that this can be achieved with a custom finder as well? If so, is that use case described anywhere?

**Comment by davidyell** [comment]
I'm using the TokenAuthenticate for my api too.

**Comment by josegonzalez** [comment]
I'd say:

- make a final cake2 release
- merge cake3 to master
- write docs for the multi-auth alternative
- depend upon JwtAuth and Xety/Cake3-CookieAuth
- remove all the code
- mark as abandoned

That way if people upgrade, we push them to the correct solutions and make it clear that this repository is not to be used directly.

**Comment by ceeram** [comment]
i did make a release for the new cake3 version as well, as people still use this.

**Comment by ceeram** [comment]
Readme updated, with a note about not being actively maintained and pointing to alternative solutions

**Comment by josegonzalez** [comment]
Can you mark it as abandoned on packagist?

**Comment by ceeram** [comment]
You have no foc powerz? Sure i can. Just can't point it to a single package
as replacement as there are different alternatives for each adapter
Op 22 dec. 2015 22:57 schreef "Jose Diaz-Gonzalez" <notifications@github.com

**Comment by josegonzalez** [comment]
I do not, apparently.

**Comment by ceeram** [comment]
apparently neither do i :) @jippi or @lorenzo might have

**Comment by devnes** [comment]
composer require friendsofcake/authenticate:dev-cake3 
[ErrorException]
  Undefined variable: baseDir

**Comment by ADmad** [comment]
It has been marked abandoned on packagist now.
